//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfSverigeServer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public Courses()
        {
            this.Holes = new HashSet<Holes>();
            this.Slopes = new HashSet<Slopes>();
        }
    
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> ClubGUID { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumberOfHoles { get; set; }
        public Nullable<int> Par { get; set; }
    
        public virtual Clubs Clubs { get; set; }
        public virtual ICollection<Holes> Holes { get; set; }
        public virtual ICollection<Slopes> Slopes { get; set; }
    }
}
