//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfSverigeServer.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class justGolfEntities : DbContext
    {
        public justGolfEntities()
            : base("name=justGolfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clubs> Clubs { get; set; }
        public DbSet<Courses> Courses { get; set; }
        public DbSet<Districts> Districts { get; set; }
        public DbSet<Holes> Holes { get; set; }
        public DbSet<Slopes> Slopes { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tees> Tees { get; set; }
    }
}
