//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfSverigeServer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Districts
    {
        public Districts()
        {
            this.Clubs = new HashSet<Clubs>();
        }
    
        public System.Guid GUID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Clubs> Clubs { get; set; }
        public virtual Districts Districts1 { get; set; }
        public virtual Districts Districts2 { get; set; }
    }
}
