//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfSverigeServer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holes
    {
        public Holes()
        {
            this.Tees = new HashSet<Tees>();
        }
    
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> CourseGUID { get; set; }
        public string Name { get; set; }
        public Nullable<double> CenterLat { get; set; }
        public Nullable<double> CenterLon { get; set; }
        public Nullable<double> FrontLat { get; set; }
        public Nullable<double> FrontLon { get; set; }
        public Nullable<double> BackLat { get; set; }
        public Nullable<double> BackLon { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Par { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual ICollection<Tees> Tees { get; set; }
    }
}
