//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfSverigeServer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slopes
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> CourseGUID { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> SlopeValue { get; set; }
        public string TeeColor { get; set; }
    
        public virtual Courses Courses { get; set; }
    }
}
