//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfSverigeServer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tees
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> HoleGUID { get; set; }
        public string Color { get; set; }
        public Nullable<int> Length { get; set; }
    
        public virtual Holes Holes { get; set; }
    }
}
